type FloorAssetType =
    | "floor"
    | "wall-top"
    | "wall-right"
    | "wall-bottom"
    | "wall-left"
    | "wall-top-left"
    | "wall-top-right"
    | "wall-bottom-left"
    | "wall-bottom-right"
    | "wall-door-left-top"
    | "wall-door-left-right"
    | "wall-door-left-bottom"
    | "wall-door-left-left"
    | "wall-door-right-top"
    | "wall-door-right-right"
    | "wall-door-right-bottom"
    | "wall-door-right-left"
    | "stairs"

type BlockAssetType = "empty" | "rock" | "wooden_frame" | "copper_ore" | "iron_ore" | "gold_ore" | "silver_ore" | "unobtainium_ore"

type BuildingAssetType =
    | "grass"
    | "bank"
    | "blacksmith"
    | "fountain"
    | "mine"
    | "restaurant"
    | "road"
    | "road-vertical"
    | "road-horizontal"
    | "abandoned-straight-top"
    | "abandoned-straight-right"
    | "abandoned-straight-bottom"
    | "abandoned-straight-left"
    | "abandoned-trap-straight-top"
    | "abandoned-trap-straight-right"
    | "abandoned-trap-straight-bottom"
    | "abandoned-trap-straight-left"
    | "abandoned-corner-top-left"
    | "abandoned-corner-top-right"
    | "abandoned-corner-bottom-left"
    | "abandoned-corner-bottom-right"
    | "abandoned-trap-corner-top-left"
    | "abandoned-trap-corner-top-right"
    | "abandoned-trap-corner-bottom-left"
    | "abandoned-trap-corner-bottom-right"

type EnemyAssetType = "zombie" | "skeleton" | "dragon"

type ItemAssetType = "wooden_sword" | "wooden_pickaxe" | "wood" | "rock_item" | "copper" | "iron" | "silver" | "gold" | "unobtainium"

export type AssetType = "player" | "table_left" | "table_right" | BuildingAssetType | BlockAssetType | FloorAssetType | EnemyAssetType | ItemAssetType