// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using game.Server.Data;

#nullable disable

namespace game.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251213095412_m2")]
    partial class m2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("RecipeTime", b =>
                {
                    b.Property<int>("RecipeTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeTimeId");

                    b.ToTable("RecipeTimes");

                    b.HasData(
                        new
                        {
                            RecipeTimeId = 1,
                            EndTime = new DateTime(2025, 12, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            RecipeId = 1,
                            StartTime = new DateTime(2025, 12, 13, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("game.Server.Models.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlockId");

                    b.HasIndex("ItemId");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            BlockId = 1,
                            BlockType = 2,
                            ItemId = 1,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 2,
                            BlockType = 1,
                            ItemId = 2,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 3,
                            BlockType = 4,
                            ItemId = 3,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 4,
                            BlockType = 3,
                            ItemId = 4,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 5,
                            BlockType = 5,
                            ItemId = 5,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 6,
                            BlockType = 6,
                            ItemId = 6,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 7,
                            BlockType = 7,
                            ItemId = 7,
                            MaxAmount = 1,
                            MinAmount = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBossDefeated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReachedHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 69,
                            BuildingType = 0,
                            IsBossDefeated = false,
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            PositionX = 0,
                            PositionY = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("FloorId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            FloorId = 6,
                            BuildingId = 69,
                            Level = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.FloorItem", b =>
                {
                    b.Property<int>("FloorItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.HasKey("FloorItemId");

                    b.HasIndex("FloorId");

                    b.ToTable("FloorItems");

                    b.HasData(
                        new
                        {
                            FloorItemId = 85,
                            FloorId = 6,
                            FloorItemType = 0,
                            PositionX = 0,
                            PositionY = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.Ingredience", b =>
                {
                    b.Property<int>("IngredienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredienceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredienceId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingrediences");

                    b.HasData(
                        new
                        {
                            IngredienceId = 1,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredienceId = 2,
                            IngredienceType = 0,
                            Order = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredienceId = 3,
                            IngredienceType = 3,
                            Order = 3,
                            RecipeId = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInBank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryItemId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            InventoryItemId = 52,
                            IsInBank = true,
                            ItemInstanceId = 85,
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0")
                        });
                });

            modelBuilder.Entity("game.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeOfGenerating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ChangeOfGenerating = 0,
                            Damage = 0,
                            Description = "Wooden Frame",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Wooden Frame",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 2,
                            ChangeOfGenerating = 0,
                            Damage = 0,
                            Description = "Rock",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Rock",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 3,
                            ChangeOfGenerating = 0,
                            Damage = 0,
                            Description = "Copper Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Copper Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 4,
                            ChangeOfGenerating = 0,
                            Damage = 0,
                            Description = "Iron Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Iron Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 5,
                            ChangeOfGenerating = 0,
                            Damage = 0,
                            Description = "Silver Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Silver Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 6,
                            ChangeOfGenerating = 0,
                            Damage = 0,
                            Description = "Gold Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Gold Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 7,
                            ChangeOfGenerating = 0,
                            Damage = 0,
                            Description = "Unobtainium Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Unobtainium Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 10,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "Wooden Sword",
                            ItemType = 0,
                            MaxDurability = 20,
                            Name = "Wooden Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 11,
                            ChangeOfGenerating = 0,
                            Damage = 2,
                            Description = "Rock Sword",
                            ItemType = 0,
                            MaxDurability = 40,
                            Name = "Rock Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 12,
                            ChangeOfGenerating = 0,
                            Damage = 3,
                            Description = "Copper Sword",
                            ItemType = 0,
                            MaxDurability = 60,
                            Name = "Copper Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 13,
                            ChangeOfGenerating = 0,
                            Damage = 4,
                            Description = "Iron Sword",
                            ItemType = 0,
                            MaxDurability = 80,
                            Name = "Iron Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 14,
                            ChangeOfGenerating = 0,
                            Damage = 5,
                            Description = "Silver Sword",
                            ItemType = 0,
                            MaxDurability = 100,
                            Name = "Silver Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 15,
                            ChangeOfGenerating = 0,
                            Damage = 6,
                            Description = "Gold Sword",
                            ItemType = 0,
                            MaxDurability = 120,
                            Name = "Gold Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 16,
                            ChangeOfGenerating = 0,
                            Damage = 7,
                            Description = "Unobtainium Sword",
                            ItemType = 0,
                            MaxDurability = 240,
                            Name = "Unobtainium Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 20,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "Wooden Axe",
                            ItemType = 1,
                            MaxDurability = 20,
                            Name = "Wooden Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 21,
                            ChangeOfGenerating = 0,
                            Damage = 2,
                            Description = "Rock Axe",
                            ItemType = 1,
                            MaxDurability = 40,
                            Name = "Rock Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 22,
                            ChangeOfGenerating = 0,
                            Damage = 3,
                            Description = "Copper Axe",
                            ItemType = 1,
                            MaxDurability = 60,
                            Name = "Copper Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 23,
                            ChangeOfGenerating = 0,
                            Damage = 4,
                            Description = "Iron Axe",
                            ItemType = 1,
                            MaxDurability = 80,
                            Name = "Iron Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 24,
                            ChangeOfGenerating = 0,
                            Damage = 5,
                            Description = "Silver Axe",
                            ItemType = 1,
                            MaxDurability = 100,
                            Name = "Silver Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 25,
                            ChangeOfGenerating = 0,
                            Damage = 6,
                            Description = "Gold Axe",
                            ItemType = 1,
                            MaxDurability = 120,
                            Name = "Gold Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 26,
                            ChangeOfGenerating = 0,
                            Damage = 7,
                            Description = "Unobtainium Axe",
                            ItemType = 1,
                            MaxDurability = 240,
                            Name = "Unobtainium Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 30,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "Wooden Pickaxe",
                            ItemType = 2,
                            MaxDurability = 20,
                            Name = "Wooden Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 31,
                            ChangeOfGenerating = 0,
                            Damage = 2,
                            Description = "Rock Pickaxe",
                            ItemType = 2,
                            MaxDurability = 40,
                            Name = "Rock Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 32,
                            ChangeOfGenerating = 0,
                            Damage = 3,
                            Description = "Copper Pickaxe",
                            ItemType = 2,
                            MaxDurability = 60,
                            Name = "Copper Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 33,
                            ChangeOfGenerating = 0,
                            Damage = 4,
                            Description = "Iron Pickaxe",
                            ItemType = 2,
                            MaxDurability = 80,
                            Name = "Iron Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 34,
                            ChangeOfGenerating = 0,
                            Damage = 5,
                            Description = "Silver Pickaxe",
                            ItemType = 2,
                            MaxDurability = 100,
                            Name = "Silver Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 35,
                            ChangeOfGenerating = 0,
                            Damage = 6,
                            Description = "Gold Pickaxe",
                            ItemType = 2,
                            MaxDurability = 120,
                            Name = "Gold Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 36,
                            ChangeOfGenerating = 0,
                            Damage = 7,
                            Description = "Unobtainium Pickaxe",
                            ItemType = 2,
                            MaxDurability = 240,
                            Name = "Unobtainium Pickaxe",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.ItemInstance", b =>
                {
                    b.Property<int>("ItemInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemInstanceId");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("game.Server.Models.Mine", b =>
                {
                    b.Property<int>("MineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("MineId");

                    b.ToTable("Mines");

                    b.HasData(
                        new
                        {
                            MineId = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.MineBlock", b =>
                {
                    b.Property<int>("MineBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineLayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MineBlockId");

                    b.HasIndex("BlockId");

                    b.HasIndex("MineLayerId");

                    b.ToTable("MineBlocks");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.Property<int>("MineLayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MineLayerID");

                    b.HasIndex("MineId");

                    b.ToTable("MineLayers");

                    b.HasData(
                        new
                        {
                            MineLayerID = 1,
                            Depth = 0,
                            MineId = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BankBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FloorItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScreenType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("FloorItemId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            BankBalance = 0,
                            Capacity = 10,
                            Money = 100,
                            Name = "Seeded Player",
                            ScreenType = 0,
                            Seed = 252
                        });
                });

            modelBuilder.Entity("game.Server.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Name = "Hamburger"
                        });
                });

            modelBuilder.Entity("game.Server.Models.Block", b =>
                {
                    b.HasOne("game.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.HasOne("game.Server.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("game.Server.Models.FloorItem", b =>
                {
                    b.HasOne("game.Server.Models.Floor", "Floor")
                        .WithMany("FloorItems")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("game.Server.Models.Ingredience", b =>
                {
                    b.HasOne("game.Server.Models.Recipe", null)
                        .WithMany("Ingrediences")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("game.Server.Models.Item", b =>
                {
                    b.HasOne("game.Server.Models.ItemInstance", null)
                        .WithMany("Items")
                        .HasForeignKey("ItemInstanceId");
                });

            modelBuilder.Entity("game.Server.Models.MineBlock", b =>
                {
                    b.HasOne("game.Server.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game.Server.Models.MineLayer", "MineLayer")
                        .WithMany("MineBlocks")
                        .HasForeignKey("MineLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("MineLayer");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.HasOne("game.Server.Models.Mine", "Mine")
                        .WithMany()
                        .HasForeignKey("MineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mine");
                });

            modelBuilder.Entity("game.Server.Models.Player", b =>
                {
                    b.HasOne("game.Server.Models.FloorItem", "FloorItem")
                        .WithMany()
                        .HasForeignKey("FloorItemId");

                    b.Navigation("FloorItem");
                });

            modelBuilder.Entity("game.Server.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.Navigation("FloorItems");
                });

            modelBuilder.Entity("game.Server.Models.ItemInstance", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.Navigation("MineBlocks");
                });

            modelBuilder.Entity("game.Server.Models.Recipe", b =>
                {
                    b.Navigation("Ingrediences");
                });
#pragma warning restore 612, 618
        }
    }
}
