// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using game.Server.Data;

#nullable disable

namespace game.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212154912_test12411111111")]
    partial class test12411111111
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("game.Server.Models.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlockId");

                    b.HasIndex("ItemId");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            BlockId = 1,
                            BlockType = 1,
                            ItemId = 1,
                            MaxAmount = 3,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 2,
                            BlockType = 3,
                            ItemId = 2,
                            MaxAmount = 1,
                            MinAmount = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBossDefeated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReachedHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 69,
                            BuildingType = 0,
                            IsBossDefeated = false,
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            PositionX = 0,
                            PositionY = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("FloorId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            FloorId = 6,
                            BuildingId = 69,
                            Level = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.FloorItem", b =>
                {
                    b.Property<int>("FloorItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.HasKey("FloorItemId");

                    b.HasIndex("FloorId");

                    b.ToTable("FloorItems");

                    b.HasData(
                        new
                        {
                            FloorItemId = 85,
                            FloorId = 6,
                            FloorItemType = 0,
                            PositionX = 0,
                            PositionY = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInBank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryItemId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            InventoryItemId = 52,
                            IsInBank = true,
                            ItemInstanceId = 85,
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0")
                        });
                });

            modelBuilder.Entity("game.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Damage = 0,
                            ItemType = 0,
                            MaxDurability = 0,
                            Name = "Stone",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 2,
                            Damage = 0,
                            ItemType = 0,
                            MaxDurability = 0,
                            Name = "Iron Ore",
                            Weight = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.ItemInstance", b =>
                {
                    b.Property<int>("ItemInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemInstanceId");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("game.Server.Models.Mine", b =>
                {
                    b.Property<int>("MineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("MineId");

                    b.ToTable("Mines");

                    b.HasData(
                        new
                        {
                            MineId = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.MineBlock", b =>
                {
                    b.Property<int>("MineBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineLayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MineBlockId");

                    b.HasIndex("BlockId");

                    b.HasIndex("MineLayerId");

                    b.ToTable("MineBlocks");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.Property<int>("MineLayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MineLayerID");

                    b.HasIndex("MineId");

                    b.ToTable("MineLayers");

                    b.HasData(
                        new
                        {
                            MineLayerID = 1,
                            Depth = 0,
                            MineId = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BankBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FloorItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScreenType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            BankBalance = 0,
                            Capacity = 10,
                            Money = 100,
                            Name = "Seeded Player",
                            ScreenType = 0,
                            Seed = 252
                        });
                });

            modelBuilder.Entity("game.Server.Models.Block", b =>
                {
                    b.HasOne("game.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.HasOne("game.Server.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("game.Server.Models.FloorItem", b =>
                {
                    b.HasOne("game.Server.Models.Floor", "Floor")
                        .WithMany("FloorItems")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("game.Server.Models.Item", b =>
                {
                    b.HasOne("game.Server.Models.ItemInstance", null)
                        .WithMany("Items")
                        .HasForeignKey("ItemInstanceId");
                });

            modelBuilder.Entity("game.Server.Models.MineBlock", b =>
                {
                    b.HasOne("game.Server.Models.Block", "Block")
                        .WithMany("MineBlocks")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game.Server.Models.MineLayer", "MineLayer")
                        .WithMany("MineBlocks")
                        .HasForeignKey("MineLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("MineLayer");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.HasOne("game.Server.Models.Mine", "Mine")
                        .WithMany()
                        .HasForeignKey("MineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mine");
                });

            modelBuilder.Entity("game.Server.Models.Block", b =>
                {
                    b.Navigation("MineBlocks");
                });

            modelBuilder.Entity("game.Server.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.Navigation("FloorItems");
                });

            modelBuilder.Entity("game.Server.Models.ItemInstance", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.Navigation("MineBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
