// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using game.Server.Data;

#nullable disable

namespace game.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208170023_rebase")]
    partial class rebase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActiveInventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubPositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubPositionY")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("ActiveInventoryItemId");

                    b.HasIndex("FloorId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            BankBalance = 0,
                            Capacity = 10,
                            Health = 20,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxHealth = 20,
                            MineId = 0,
                            Money = 100,
                            Name = "Seeded Player",
                            PositionX = 0,
                            PositionY = 0,
                            ScreenType = 0,
                            Seed = 252,
                            SubPositionX = 0,
                            SubPositionY = 0
                        });
                });

            modelBuilder.Entity("RecipeTime", b =>
                {
                    b.Property<int>("RecipeTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeTimeId");

                    b.ToTable("RecipeTimes");

                    b.HasData(
                        new
                        {
                            RecipeTimeId = 1,
                            EndTime = new DateTime(2025, 12, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            RecipeId = 1,
                            StartTime = new DateTime(2025, 12, 13, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Save", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SaveString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("game.Server.Models.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlockId");

                    b.HasIndex("ItemId");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            BlockId = 1,
                            BlockType = 2,
                            ItemId = 1,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 2,
                            BlockType = 1,
                            ItemId = 2,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 3,
                            BlockType = 4,
                            ItemId = 3,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 4,
                            BlockType = 3,
                            ItemId = 4,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 5,
                            BlockType = 5,
                            ItemId = 5,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 6,
                            BlockType = 6,
                            ItemId = 6,
                            MaxAmount = 1,
                            MinAmount = 1
                        },
                        new
                        {
                            BlockId = 7,
                            BlockType = 7,
                            ItemId = 7,
                            MaxAmount = 1,
                            MinAmount = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.Blueprint", b =>
                {
                    b.Property<int>("BlueprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlueprintId");

                    b.HasIndex("ItemId");

                    b.ToTable("Blueprints");

                    b.HasData(
                        new
                        {
                            BlueprintId = 1,
                            ItemId = 10,
                            Price = 5
                        },
                        new
                        {
                            BlueprintId = 3,
                            ItemId = 11,
                            Price = 10
                        },
                        new
                        {
                            BlueprintId = 4,
                            ItemId = 12,
                            Price = 20
                        },
                        new
                        {
                            BlueprintId = 5,
                            ItemId = 13,
                            Price = 40
                        },
                        new
                        {
                            BlueprintId = 6,
                            ItemId = 14,
                            Price = 80
                        },
                        new
                        {
                            BlueprintId = 7,
                            ItemId = 15,
                            Price = 150
                        },
                        new
                        {
                            BlueprintId = 8,
                            ItemId = 16,
                            Price = 500
                        },
                        new
                        {
                            BlueprintId = 9,
                            ItemId = 20,
                            Price = 5
                        },
                        new
                        {
                            BlueprintId = 10,
                            ItemId = 21,
                            Price = 10
                        },
                        new
                        {
                            BlueprintId = 11,
                            ItemId = 22,
                            Price = 20
                        },
                        new
                        {
                            BlueprintId = 12,
                            ItemId = 23,
                            Price = 40
                        },
                        new
                        {
                            BlueprintId = 13,
                            ItemId = 24,
                            Price = 80
                        },
                        new
                        {
                            BlueprintId = 14,
                            ItemId = 25,
                            Price = 150
                        },
                        new
                        {
                            BlueprintId = 15,
                            ItemId = 26,
                            Price = 500
                        },
                        new
                        {
                            BlueprintId = 2,
                            ItemId = 30,
                            Price = 5
                        },
                        new
                        {
                            BlueprintId = 16,
                            ItemId = 31,
                            Price = 10
                        },
                        new
                        {
                            BlueprintId = 17,
                            ItemId = 32,
                            Price = 20
                        },
                        new
                        {
                            BlueprintId = 18,
                            ItemId = 33,
                            Price = 40
                        },
                        new
                        {
                            BlueprintId = 19,
                            ItemId = 34,
                            Price = 80
                        },
                        new
                        {
                            BlueprintId = 20,
                            ItemId = 35,
                            Price = 150
                        },
                        new
                        {
                            BlueprintId = 21,
                            ItemId = 36,
                            Price = 500
                        },
                        new
                        {
                            BlueprintId = 22,
                            ItemId = 40,
                            Price = 500
                        },
                        new
                        {
                            BlueprintId = 23,
                            ItemId = 41,
                            Price = 500
                        },
                        new
                        {
                            BlueprintId = 24,
                            ItemId = 42,
                            Price = 500
                        },
                        new
                        {
                            BlueprintId = 25,
                            ItemId = 100,
                            Price = 10000
                        });
                });

            modelBuilder.Entity("game.Server.Models.BlueprintPlayer", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BlueprintId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "BlueprintId");

                    b.HasIndex("BlueprintId");

                    b.ToTable("BlueprintPlayers");
                });

            modelBuilder.Entity("game.Server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBossDefeated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReachedHeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 69,
                            BuildingType = 0,
                            IsBossDefeated = false,
                            PlayerId = new Guid("4b1e8a93-7d92-4f7f-80c1-525c345b85e0"),
                            PositionX = 0,
                            PositionY = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.Chest", b =>
                {
                    b.Property<int>("ChestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChestId");

                    b.HasIndex("FloorItemId")
                        .IsUnique();

                    b.ToTable("Chests");
                });

            modelBuilder.Entity("game.Server.Models.Crafting", b =>
                {
                    b.Property<int>("CraftingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlueprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CraftingId");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("ItemId");

                    b.ToTable("Craftings");

                    b.HasData(
                        new
                        {
                            CraftingId = 1,
                            Amount = 2,
                            BlueprintId = 1,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 2,
                            Amount = 3,
                            BlueprintId = 2,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 40,
                            Amount = 3,
                            BlueprintId = 9,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 3,
                            Amount = 2,
                            BlueprintId = 3,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 4,
                            Amount = 3,
                            BlueprintId = 3,
                            ItemId = 2
                        },
                        new
                        {
                            CraftingId = 5,
                            Amount = 2,
                            BlueprintId = 4,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 6,
                            Amount = 5,
                            BlueprintId = 4,
                            ItemId = 3
                        },
                        new
                        {
                            CraftingId = 7,
                            Amount = 3,
                            BlueprintId = 5,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 8,
                            Amount = 6,
                            BlueprintId = 5,
                            ItemId = 4
                        },
                        new
                        {
                            CraftingId = 9,
                            Amount = 3,
                            BlueprintId = 6,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 10,
                            Amount = 8,
                            BlueprintId = 6,
                            ItemId = 5
                        },
                        new
                        {
                            CraftingId = 11,
                            Amount = 4,
                            BlueprintId = 7,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 12,
                            Amount = 9,
                            BlueprintId = 7,
                            ItemId = 6
                        },
                        new
                        {
                            CraftingId = 13,
                            Amount = 5,
                            BlueprintId = 8,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 14,
                            Amount = 10,
                            BlueprintId = 8,
                            ItemId = 7
                        },
                        new
                        {
                            CraftingId = 16,
                            Amount = 3,
                            BlueprintId = 10,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 17,
                            Amount = 3,
                            BlueprintId = 10,
                            ItemId = 2
                        },
                        new
                        {
                            CraftingId = 41,
                            Amount = 3,
                            BlueprintId = 11,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 42,
                            Amount = 5,
                            BlueprintId = 11,
                            ItemId = 3
                        },
                        new
                        {
                            CraftingId = 18,
                            Amount = 4,
                            BlueprintId = 12,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 19,
                            Amount = 7,
                            BlueprintId = 12,
                            ItemId = 4
                        },
                        new
                        {
                            CraftingId = 43,
                            Amount = 4,
                            BlueprintId = 13,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 44,
                            Amount = 9,
                            BlueprintId = 13,
                            ItemId = 5
                        },
                        new
                        {
                            CraftingId = 45,
                            Amount = 5,
                            BlueprintId = 14,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 46,
                            Amount = 10,
                            BlueprintId = 14,
                            ItemId = 6
                        },
                        new
                        {
                            CraftingId = 20,
                            Amount = 5,
                            BlueprintId = 15,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 21,
                            Amount = 10,
                            BlueprintId = 15,
                            ItemId = 7
                        },
                        new
                        {
                            CraftingId = 22,
                            Amount = 3,
                            BlueprintId = 16,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 23,
                            Amount = 4,
                            BlueprintId = 16,
                            ItemId = 2
                        },
                        new
                        {
                            CraftingId = 47,
                            Amount = 3,
                            BlueprintId = 17,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 48,
                            Amount = 6,
                            BlueprintId = 17,
                            ItemId = 3
                        },
                        new
                        {
                            CraftingId = 49,
                            Amount = 4,
                            BlueprintId = 18,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 50,
                            Amount = 8,
                            BlueprintId = 18,
                            ItemId = 4
                        },
                        new
                        {
                            CraftingId = 24,
                            Amount = 4,
                            BlueprintId = 19,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 25,
                            Amount = 8,
                            BlueprintId = 19,
                            ItemId = 5
                        },
                        new
                        {
                            CraftingId = 51,
                            Amount = 5,
                            BlueprintId = 20,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 52,
                            Amount = 10,
                            BlueprintId = 20,
                            ItemId = 6
                        },
                        new
                        {
                            CraftingId = 26,
                            Amount = 5,
                            BlueprintId = 21,
                            ItemId = 1
                        },
                        new
                        {
                            CraftingId = 27,
                            Amount = 10,
                            BlueprintId = 21,
                            ItemId = 7
                        });
                });

            modelBuilder.Entity("game.Server.Models.Enemy", b =>
                {
                    b.Property<int>("EnemyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnemyId");

                    b.HasIndex("FloorItemId")
                        .IsUnique();

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("FloorId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            FloorId = 6,
                            BuildingId = 69,
                            Level = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.FloorItem", b =>
                {
                    b.Property<int>("FloorItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FloorItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.HasKey("FloorItemId");

                    b.HasIndex("FloorId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("FloorItems");

                    b.HasData(
                        new
                        {
                            FloorItemId = 85,
                            FloorId = 6,
                            FloorItemType = 0,
                            PositionX = 0,
                            PositionY = 0
                        });
                });

            modelBuilder.Entity("game.Server.Models.Ingredience", b =>
                {
                    b.Property<int>("IngredienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredienceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredienceId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingrediences");

                    b.HasData(
                        new
                        {
                            IngredienceId = 1,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredienceId = 2,
                            IngredienceType = 0,
                            Order = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredienceId = 3,
                            IngredienceType = 3,
                            Order = 3,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredienceId = 4,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredienceId = 5,
                            IngredienceType = 0,
                            Order = 2,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredienceId = 6,
                            IngredienceType = 7,
                            Order = 3,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredienceId = 7,
                            IngredienceType = 3,
                            Order = 4,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredienceId = 8,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredienceId = 9,
                            IngredienceType = 0,
                            Order = 2,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredienceId = 10,
                            IngredienceType = 6,
                            Order = 3,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredienceId = 11,
                            IngredienceType = 3,
                            Order = 4,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredienceId = 12,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredienceId = 13,
                            IngredienceType = 1,
                            Order = 2,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredienceId = 14,
                            IngredienceType = 4,
                            Order = 3,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredienceId = 15,
                            IngredienceType = 5,
                            Order = 4,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredienceId = 16,
                            IngredienceType = 1,
                            Order = 5,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredienceId = 17,
                            IngredienceType = 3,
                            Order = 6,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredienceId = 18,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredienceId = 19,
                            IngredienceType = 6,
                            Order = 2,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredienceId = 20,
                            IngredienceType = 1,
                            Order = 3,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredienceId = 21,
                            IngredienceType = 4,
                            Order = 4,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredienceId = 22,
                            IngredienceType = 3,
                            Order = 5,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredienceId = 23,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredienceId = 24,
                            IngredienceType = 5,
                            Order = 2,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredienceId = 25,
                            IngredienceType = 0,
                            Order = 3,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredienceId = 26,
                            IngredienceType = 1,
                            Order = 4,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredienceId = 27,
                            IngredienceType = 3,
                            Order = 5,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredienceId = 28,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredienceId = 29,
                            IngredienceType = 5,
                            Order = 2,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredienceId = 30,
                            IngredienceType = 4,
                            Order = 3,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredienceId = 31,
                            IngredienceType = 0,
                            Order = 4,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredienceId = 32,
                            IngredienceType = 6,
                            Order = 5,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredienceId = 33,
                            IngredienceType = 1,
                            Order = 6,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredienceId = 34,
                            IngredienceType = 3,
                            Order = 7,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredienceId = 35,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredienceId = 36,
                            IngredienceType = 1,
                            Order = 2,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredienceId = 37,
                            IngredienceType = 0,
                            Order = 3,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredienceId = 38,
                            IngredienceType = 3,
                            Order = 4,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredienceId = 39,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredienceId = 40,
                            IngredienceType = 0,
                            Order = 2,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredienceId = 41,
                            IngredienceType = 0,
                            Order = 3,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredienceId = 42,
                            IngredienceType = 0,
                            Order = 4,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredienceId = 43,
                            IngredienceType = 3,
                            Order = 5,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredienceId = 44,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredienceId = 45,
                            IngredienceType = 5,
                            Order = 2,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredienceId = 46,
                            IngredienceType = 0,
                            Order = 3,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredienceId = 47,
                            IngredienceType = 6,
                            Order = 4,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredienceId = 48,
                            IngredienceType = 4,
                            Order = 5,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredienceId = 49,
                            IngredienceType = 3,
                            Order = 6,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredienceId = 50,
                            IngredienceType = 2,
                            Order = 1,
                            RecipeId = 11
                        },
                        new
                        {
                            IngredienceId = 51,
                            IngredienceType = 1,
                            Order = 2,
                            RecipeId = 11
                        },
                        new
                        {
                            IngredienceId = 52,
                            IngredienceType = 4,
                            Order = 3,
                            RecipeId = 11
                        },
                        new
                        {
                            IngredienceId = 53,
                            IngredienceType = 7,
                            Order = 4,
                            RecipeId = 11
                        },
                        new
                        {
                            IngredienceId = 54,
                            IngredienceType = 0,
                            Order = 5,
                            RecipeId = 11
                        },
                        new
                        {
                            IngredienceId = 55,
                            IngredienceType = 6,
                            Order = 6,
                            RecipeId = 11
                        },
                        new
                        {
                            IngredienceId = 56,
                            IngredienceType = 3,
                            Order = 7,
                            RecipeId = 11
                        });
                });

            modelBuilder.Entity("game.Server.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInBank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("ItemInstanceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventoryItem");
                });

            modelBuilder.Entity("game.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeOfGenerating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ChangeOfGenerating = 6,
                            Damage = 0,
                            Description = "Wooden Frame",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Wooden Frame",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 2,
                            ChangeOfGenerating = 95,
                            Damage = 0,
                            Description = "Rock",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Rock",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 3,
                            ChangeOfGenerating = 7,
                            Damage = 0,
                            Description = "Copper Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Copper Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 4,
                            ChangeOfGenerating = 6,
                            Damage = 0,
                            Description = "Iron Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Iron Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 5,
                            ChangeOfGenerating = 7,
                            Damage = 0,
                            Description = "Silver Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Silver Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 6,
                            ChangeOfGenerating = 6,
                            Damage = 0,
                            Description = "Gold Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Gold Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 7,
                            ChangeOfGenerating = 1,
                            Damage = 0,
                            Description = "Unobtainium Ore",
                            ItemType = 4,
                            MaxDurability = 0,
                            Name = "Unobtainium Ore",
                            Weight = 0
                        },
                        new
                        {
                            ItemId = 10,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "Wooden Sword",
                            ItemType = 0,
                            MaxDurability = 20,
                            Name = "Wooden Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 11,
                            ChangeOfGenerating = 0,
                            Damage = 2,
                            Description = "Rock Sword",
                            ItemType = 0,
                            MaxDurability = 40,
                            Name = "Rock Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 12,
                            ChangeOfGenerating = 0,
                            Damage = 3,
                            Description = "Copper Sword",
                            ItemType = 0,
                            MaxDurability = 60,
                            Name = "Copper Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 13,
                            ChangeOfGenerating = 0,
                            Damage = 4,
                            Description = "Iron Sword",
                            ItemType = 0,
                            MaxDurability = 80,
                            Name = "Iron Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 14,
                            ChangeOfGenerating = 0,
                            Damage = 5,
                            Description = "Silver Sword",
                            ItemType = 0,
                            MaxDurability = 100,
                            Name = "Silver Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 15,
                            ChangeOfGenerating = 0,
                            Damage = 6,
                            Description = "Gold Sword",
                            ItemType = 0,
                            MaxDurability = 120,
                            Name = "Gold Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 16,
                            ChangeOfGenerating = 0,
                            Damage = 7,
                            Description = "Unobtainium Sword",
                            ItemType = 0,
                            MaxDurability = 240,
                            Name = "Unobtainium Sword",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 20,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "Wooden Axe",
                            ItemType = 1,
                            MaxDurability = 20,
                            Name = "Wooden Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 21,
                            ChangeOfGenerating = 0,
                            Damage = 2,
                            Description = "Rock Axe",
                            ItemType = 1,
                            MaxDurability = 40,
                            Name = "Rock Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 22,
                            ChangeOfGenerating = 0,
                            Damage = 3,
                            Description = "Copper Axe",
                            ItemType = 1,
                            MaxDurability = 60,
                            Name = "Copper Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 23,
                            ChangeOfGenerating = 0,
                            Damage = 4,
                            Description = "Iron Axe",
                            ItemType = 1,
                            MaxDurability = 80,
                            Name = "Iron Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 24,
                            ChangeOfGenerating = 0,
                            Damage = 5,
                            Description = "Silver Axe",
                            ItemType = 1,
                            MaxDurability = 100,
                            Name = "Silver Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 25,
                            ChangeOfGenerating = 0,
                            Damage = 6,
                            Description = "Gold Axe",
                            ItemType = 1,
                            MaxDurability = 120,
                            Name = "Gold Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 26,
                            ChangeOfGenerating = 0,
                            Damage = 7,
                            Description = "Unobtainium Axe",
                            ItemType = 1,
                            MaxDurability = 240,
                            Name = "Unobtainium Axe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 30,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "Wooden Pickaxe",
                            ItemType = 2,
                            MaxDurability = 20,
                            Name = "Wooden Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 31,
                            ChangeOfGenerating = 0,
                            Damage = 2,
                            Description = "Rock Pickaxe",
                            ItemType = 2,
                            MaxDurability = 40,
                            Name = "Rock Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 32,
                            ChangeOfGenerating = 0,
                            Damage = 3,
                            Description = "Copper Pickaxe",
                            ItemType = 2,
                            MaxDurability = 60,
                            Name = "Copper Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 33,
                            ChangeOfGenerating = 0,
                            Damage = 4,
                            Description = "Iron Pickaxe",
                            ItemType = 2,
                            MaxDurability = 80,
                            Name = "Iron Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 34,
                            ChangeOfGenerating = 0,
                            Damage = 5,
                            Description = "Silver Pickaxe",
                            ItemType = 2,
                            MaxDurability = 100,
                            Name = "Silver Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 35,
                            ChangeOfGenerating = 0,
                            Damage = 6,
                            Description = "Gold Pickaxe",
                            ItemType = 2,
                            MaxDurability = 120,
                            Name = "Gold Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 36,
                            ChangeOfGenerating = 0,
                            Damage = 7,
                            Description = "Unobtainium Pickaxe",
                            ItemType = 2,
                            MaxDurability = 240,
                            Name = "Unobtainium Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 39,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "Rented Pickaxe",
                            ItemType = 2,
                            MaxDurability = 15,
                            Name = "Rented Pickaxe",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 40,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "This thing heals",
                            ItemType = 3,
                            MaxDurability = 1,
                            Name = "Healing Potion",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 41,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "+5 hp",
                            ItemType = 3,
                            MaxDurability = 1,
                            Name = "God Potion",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 42,
                            ChangeOfGenerating = 0,
                            Damage = 1,
                            Description = "+5 inventory space",
                            ItemType = 3,
                            MaxDurability = 1,
                            Name = "Muscle Potion",
                            Weight = 1
                        },
                        new
                        {
                            ItemId = 100,
                            ChangeOfGenerating = 0,
                            Damage = 100,
                            Description = "Drop this into fountain to win",
                            ItemType = 0,
                            MaxDurability = 1000000,
                            Name = "Mythical Sword",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.ItemInstance", b =>
                {
                    b.Property<int>("ItemInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemInstanceId");

                    b.HasIndex("ChestId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("game.Server.Models.ItemMineBlock", b =>
                {
                    b.Property<int>("ItemInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineBlockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemInstanceId", "MineBlockId");

                    b.HasIndex("MineBlockId");

                    b.ToTable("ItemMineBlock");
                });

            modelBuilder.Entity("game.Server.Models.Mine", b =>
                {
                    b.Property<int>("MineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("MineId");

                    b.ToTable("Mines");

                    b.HasData(
                        new
                        {
                            MineId = 1,
                            PlayerId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("game.Server.Models.MineBlock", b =>
                {
                    b.Property<int>("MineBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineLayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MineBlockId");

                    b.HasIndex("BlockId");

                    b.HasIndex("MineLayerId");

                    b.ToTable("MineBlocks");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.Property<int>("MineLayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MineLayerID");

                    b.HasIndex("MineId");

                    b.ToTable("MineLayers");

                    b.HasData(
                        new
                        {
                            MineLayerID = 1,
                            Depth = 0,
                            MineId = 1
                        });
                });

            modelBuilder.Entity("game.Server.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Name = "Classic Hamburger"
                        },
                        new
                        {
                            RecipeId = 2,
                            Name = "Cheeseburger"
                        },
                        new
                        {
                            RecipeId = 3,
                            Name = "Bacon Burger"
                        },
                        new
                        {
                            RecipeId = 4,
                            Name = "Veggie Deluxe"
                        },
                        new
                        {
                            RecipeId = 5,
                            Name = "BLT Sandwich"
                        },
                        new
                        {
                            RecipeId = 6,
                            Name = "Chicken Sandwich"
                        },
                        new
                        {
                            RecipeId = 7,
                            Name = "The Works Burger"
                        },
                        new
                        {
                            RecipeId = 8,
                            Name = "Simple Salad Burger"
                        },
                        new
                        {
                            RecipeId = 9,
                            Name = "Triple Meat Stack"
                        },
                        new
                        {
                            RecipeId = 10,
                            Name = "Saucy Bacon Tomato Burger"
                        },
                        new
                        {
                            RecipeId = 11,
                            Name = "Bacon Cheeseburger Deluxe"
                        });
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.HasOne("game.Server.Models.InventoryItem", "ActiveInventoryItem")
                        .WithMany()
                        .HasForeignKey("ActiveInventoryItemId");

                    b.HasOne("game.Server.Models.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");

                    b.Navigation("ActiveInventoryItem");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("game.Server.Models.Block", b =>
                {
                    b.HasOne("game.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("game.Server.Models.Blueprint", b =>
                {
                    b.HasOne("game.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("game.Server.Models.BlueprintPlayer", b =>
                {
                    b.HasOne("game.Server.Models.Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("game.Server.Models.Chest", b =>
                {
                    b.HasOne("game.Server.Models.FloorItem", null)
                        .WithOne("Chest")
                        .HasForeignKey("game.Server.Models.Chest", "FloorItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("game.Server.Models.Crafting", b =>
                {
                    b.HasOne("game.Server.Models.Blueprint", "Blueprint")
                        .WithMany("Craftings")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("game.Server.Models.Enemy", b =>
                {
                    b.HasOne("game.Server.Models.FloorItem", null)
                        .WithOne("Enemy")
                        .HasForeignKey("game.Server.Models.Enemy", "FloorItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game.Server.Models.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId");

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.HasOne("game.Server.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("game.Server.Models.FloorItem", b =>
                {
                    b.HasOne("game.Server.Models.Floor", "Floor")
                        .WithMany("FloorItems")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game.Server.Models.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Floor");

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("game.Server.Models.Ingredience", b =>
                {
                    b.HasOne("game.Server.Models.Recipe", null)
                        .WithMany("Ingrediences")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("game.Server.Models.InventoryItem", b =>
                {
                    b.HasOne("game.Server.Models.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("game.Server.Models.ItemInstance", b =>
                {
                    b.HasOne("game.Server.Models.Chest", "Chest")
                        .WithMany("ItemInstances")
                        .HasForeignKey("ChestId");

                    b.HasOne("game.Server.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chest");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("game.Server.Models.ItemMineBlock", b =>
                {
                    b.HasOne("game.Server.Models.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game.Server.Models.MineBlock", "MineBlock")
                        .WithMany()
                        .HasForeignKey("MineBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInstance");

                    b.Navigation("MineBlock");
                });

            modelBuilder.Entity("game.Server.Models.MineBlock", b =>
                {
                    b.HasOne("game.Server.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game.Server.Models.MineLayer", "MineLayer")
                        .WithMany("MineBlocks")
                        .HasForeignKey("MineLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("MineLayer");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.HasOne("game.Server.Models.Mine", null)
                        .WithMany("MineLayers")
                        .HasForeignKey("MineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("game.Server.Models.Blueprint", b =>
                {
                    b.Navigation("Craftings");
                });

            modelBuilder.Entity("game.Server.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("game.Server.Models.Chest", b =>
                {
                    b.Navigation("ItemInstances");
                });

            modelBuilder.Entity("game.Server.Models.Floor", b =>
                {
                    b.Navigation("FloorItems");
                });

            modelBuilder.Entity("game.Server.Models.FloorItem", b =>
                {
                    b.Navigation("Chest");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("game.Server.Models.Mine", b =>
                {
                    b.Navigation("MineLayers");
                });

            modelBuilder.Entity("game.Server.Models.MineLayer", b =>
                {
                    b.Navigation("MineBlocks");
                });

            modelBuilder.Entity("game.Server.Models.Recipe", b =>
                {
                    b.Navigation("Ingrediences");
                });
#pragma warning restore 612, 618
        }
    }
}
